name: "Docker Stack Deploy"
description: "Deploy a Docker Compose or Stack to a Remote Host over SSH w/ Optional Registry Authentication"
author: "Shane"
branding:
  icon: "layers"
  color: "green"

inputs:
  name:
    description: "Docker Stack Name"
    required: true
  file:
    description: "Docker Compose File"
    required: false
    default: "docker-compose.yaml"
  compose:
    description: "Use Compose"
    required: false
    default: "false"
  compose_args:
    description: "Compose Arguments"
    required: false
    default: "--remove-orphans --force-recreate"
  host:
    description: "Docker Host"
    required: true
  port:
    description: "Docker Port"
    required: false
    default: "22"
  user:
    description: "Docker User"
    required: true
  pass:
    description: "Docker Pass"
    required: false
  ssh_key:
    description: "SSH Key File"
    required: false
  env_file:
    description: "Environment File"
    required: false
  detach:
    description: "Detach Flag"
    required: false
    default: "true"
  prune:
    description: "Prune Flag"
    required: false
    default: "false"
  resolve_image:
    description: "Resolve Image Flag"
    required: false
    default: "always"
  registry_auth:
    description: "Enable Registry Auth"
    required: false
  registry_host:
    description: "Registry Auth Hostname"
    required: false
  registry_user:
    description: "Registry Auth Username"
    required: false
  registry_pass:
    description: "Registry Auth Password"
    required: false
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"

runs:
  using: "docker"
  image: "Dockerfile"
