name: "Docker Stack Deploy"
description: "Deploy a Docker Stack"
author: "Shane"
branding:
  icon: "layers"
  color: "green"

inputs:
  host:
    description: "Docker Host"
    required: true
  user:
    description: "Docker User"
    required: true
  pass:
    description: "Docker Pass"
    required: false
  port:
    description: "Docker Port"
    default: "22"
    required: false
  ssh_key:
    description: "SSH Key File"
    required: false
  name:
    description: "Docker Stack Name"
    required: true
  file:
    description: "Docker Compose File"
    default: "docker-compose.yaml"
    required: false
  env_file:
    description: "Environment File"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
